---
output:
  html_document:
    theme: yeti
---

<style type="text/css">
body{ /* Normal  */ font-size: 16px; font-family: Arial; color:black;  line-height: 1.8;}
td {  /* Table  */ font-size: 8px;}
h1.title {font-size: 38px; color: DarkRed;}
h1 { /* Header 1 */ font-size: 28px; color: Black;}
h2 { /* Header 2 */ font-size: 22px; color: Black;}
h3 { /* Header 3 */ font-size: 18px; color: Black; font-weight: bold;}
code.r{ /* Code block */ font-size: 12px;}
pre { /* Code block - determines code spacing between lines */ font-size: 14px;}
.navbar {
  display: flex; /* Align items horizontally */
  justify-content: space-between; /* Space out items */
  align-items: start; /* Top vertical end */
  #align-items: center; /* Center items vertically */
  #align-items: flex-end; /* Lower vertical end */
  height: 175px; /* Set specific height for navbar, adjust as needed */
  background-color: #000033; /* Dark blue color */
}
.navbar-nav a {
  text-decoration: none; /* Optional: remove underline from links */
  color: black; /* Optional: set link color */
}
.navbar-nav li {
  padding: 10px 0 0 0; /* Add padding to top of menu items */
  padding: 0 10px; /* Optional: add padding to menu items */
}
/* Ensure the parent container is relatively positioned */
.parent-container {
  position: relative;
}
.footer {
  background-color: #000033; /* Dark blue color */
  color: white;
  text-align: center;
  padding: 10px 0; /* Adjust padding as needed */
  width: 100%; /* Ensure the footer spans the full width */
  position: fixed; /* Fixed position */
  bottom: 0; /* Stick to the bottom of the viewport */
  left: 0; /* Align the footer to the left edge */
  box-sizing: border-box; /* Include padding in the element's total width and height */
  z-index: 1000; /* Ensure it stays on top of other content */
}
.footer a {
  color: white; /* Footer links color */
  text-decoration: none; /* Remove underline from links */
}
.footer a:hover {
  text-decoration: underline; /* Underline on hover */
}
}</style>

This page describes Brian Folt's personal philosophy toward research, teaching, and mentorship in the field of applied ecology.

## [**Philosophy**]{.ul}

Native species, ecosystems, and natural ways of life are rapidly being lost due to pervasive anthropogenic stressors around the world. I feel an **ethical duty** as a biologist to conduct research that goes beyond testing theory and instead (1) generates **practical solutions** for natural resource management problems and (2) trains **diverse cohorts** of **scientists and practitioners**. To this end, I describe here my professional philosophy, including my **research interests and approach**, philosophy toward **teaching and mentorship**, and approach to ensuring **diversity and inclusion** in the field of wildlife biology.

### [**Research Statement**]{.ul}
  
I am an **applied population biologist** that focuses on developing management strategies for at-risk species and ecosystems in the face of global change. I conduct fundamental research that tests hypotheses about how **habitats** and **landscapes** influence **animal population dynamics**, and then I work to understand how populations, habitats, and landscapes can be **managed** in ways that maximize important societal **values**. My research program combines data collection in the field with modern advances in quantitative analytical methods to address the needs of wildlife managers and conservationists. My quantitative expertise includes using **Bayesian hierarchical methods** to estimate and model how **environmental variation influences the demographic rates and population dynamics** of populations, species, and wildlife communities through time. I have worked with diverse organisms (mammals, amphibians, reptiles), ecosystems (western rangelands, long-leaf pine forests, tropical rain forests), and questions (theoretical and applied), but my research is currently centered around two themes: the effects of multiple stressors on declining species, and decision analysis to support natural resource management decisions. My work spans different spatial and temporal scales (e.g., **local to range-wide spatial scales**) and takes advantage of advanced quantitative tools that are useful for projections and supporting decisions. **Collaboration** is critical and I work closely with **partner agencies**, such as the Alabama Dept. of Conservation and Natural Resources, U.S. Fish and Wildlife Service, and Bureau of Land Management, to **co-produce** applied science that suits agency needs. Through targeted research within these partnerships, my over-arching goal is to provide science to support smart decisions in natural resource management.

I want my work to support regional management needs; to this end, I have studied the effects of **multiple anthropogenic stressors** on vertebrate populations. I often use **risk assessment** approaches to understand the many ways in which species can be threatened by global change, including climate change, sea-level rise, altered habitat management, urbanization, human-subsidized predators, wildfire, and invasive species. I recently modeled how Gopher Tortoise populations might persist in a changing world with diverse anthropogenic threats, which produced a risk assessment useful for a federal Species Status Assessment. I am currently involved in efforts seeking to understand how threats and management actions in the Mojave Desert ecosystem might influence the population dynamics of the federally listed **Mojave Desert Tortoise** under future conditions of global change. I am also interested in supporting ecosystem resilience through better management of **ecosystem engineers**, such as gopher tortoises and federally protected 'wild horses' and 'wild burros'. In particular, I have worked with the **Bureau of Land Management** to better manage horse populations and minimize their effects on western rangeland ecosystems by providing **hierarchical models of population dynamics** and predictive models of tradeoffs among management alternatives (\href{https://rconnect.usgs.gov/popequus/}{\emph{PopEquus}}).

At the **Nevada Cooperative Fish and Wildlife Research Unit**, I hope to continue to nurture strong working relationships with state and federal governmental agencies to address wildlife and natural resource management issues, such as how global change is influencing non-game and game species in Nevada and the West. To do so, I will develop effective working relationships with managers and decision makers and support their decision processes with a **structured-decision making** and **co-production** toolkit. Past examples of my capacity for decision-support research includes facilitating meetings with decision makers and stakeholders to (1) frame problems, objectives, and management alternatives, and then (2) build predictive modeling **tools** to evaluate the consequences and tradeoffs among alternatives being considered. Importantly, this framework helps managers make decisions that balance **multiple competing objectives**, such as the reintroduction of endangered species, management of invasive species (e.g., wild horses), ecosystem restoration, and minimizing cost, all while accounting for the diverse and varying values of stakeholders. At the Nevada Co-op Unit, my lab group will continue to use **structured decision making** and **co-production** to clearly frame problems, generate shared understanding of issues, and build **tools** to identify alternatives that balance competing objectives of decision makers and stakeholders for contentious and difficult management problems in the Great Basin ecosystem. Because Nevada is the epicenter of the horse management problem in North America, I hope to continue to support research needs for this problem.

#### [**Teaching Philosophy**]{.ul}

I believe that the future of wildlife management is rooted in strong **education** about the natural world and how it can be **managed**. To this end, I have worked to educate and train future scientists from **diverse constuencies** by mentoring students (\emph{n} = 9), teaching university courses and workshops, and engaging in public outreach activities. My teaching style blends **fun lectures** with active learning through group discussions and individual/group projects in the **classroom, lab, or field**. I aim to teach students **practical skills** in study design, analysis, technical writing, and science communication -- often through project-based assignments -- so students will be **capable and confident** when they leave the classroom and head out into the professional community. Given my research strengths in applied population biology and structured decision making, I hope to offer classes in **quantitative ecology** and **decision analysis for natural resource management** at the **University of Nevada - Reno** (UNR), and also mentoring students in this topics.

My ultimate goal in graduate student mentorship is to teach students the **fundamental skills** necessary for their independence as professionals in our field. To do this, students in my laboratory will benefit from **regular lab meetings** where we will discuss literature, work on lab projects, share results of ongoing research (e.g., proposals, conference presentations, thesis chapters), and troubleshoot problems. The laboratory will include students and professionals at different educational levels (e.g., MS, PhD, post-doc) to provide opportunities for within-lab learning and mentorship from diverse backgrounds. However, there is no single approach to student mentorship, so I will be intentional about working to **understand the interests and goals** of each student during regular 1-on-1 meetings and **catering their experience** (e.g., projects, coursework, committees, conferences, professional network) to best set them up for success along their desired career path. The graduate student experience can be a challenging one, and I will be **sensitive and supportive** of student during the ups-and-downs of their program. Additionally, I recognize that I am relatively early in my career, and I will regularly seek feedback from students and peers about how I can improve mentorship and better serve students.

#### [**Diversity and Inclusion in Wildlife Biology**]{.ul}

I believe that **diversity, equity, and inclusion (DEI)** are critical to the professional field of wildlife biology because a more diverse workforce will improve our work, better engage the public, and ultimately enact positive societal change into the future. To this end, I aim to promote DEI in wildlife biology through three mechanisms: **environment**, **recruitment**, and **retention**. I will create an **inclusive laboratory environment** by embracing DEI as core values that are embedded within lab activities. Examples include, but are not limited to, having **explicit lab policies** that promote inclusivity (e.g., harrassment and accommodation policies), participating in scientific societies and conferences that serve underrepresented groups (e.g., Society for the Advancement of Chicanos and Native Americans in Science), and seeking out **research collaborations** with institutions that support diversity initiatives (e.g., tribal colleges, HBCUs, NSF Research Experience for Undergraduate [REU] Programs). These activities and societies will then provide opportunities for **recruitment** of promising students from historically underrepresented groups in wildlife biology to join our lab. Diversity will be **celebrated** within the lab and will ultimately benefit our work through different backgrounds, life experiences, and viewpoints. For example, I am proud of the diverse students I have mentored in undergraduate and graduate studies to date, four of which went on to pursue and receive graduate degrees in wildlife sciences.

<br>

<!-- Simple Dark Blue Footer -->
<div class="footer">
  <p> Copyright &copy; Brian Folt, 2024--present. All rights reserved.</p>
  </p>
</div>